travis:
  secure:
    BINSTAR_TOKEN: CFEeM7BKQ+B+xLffpoShftqLySbSm7g6nT5jGkFno8KoP679NINEXZQKcc6PZS5eJEbju4JStQgrgFzkzV+1/hiZLsTOmi36Gd6nOML7/LO9yLKLv1aNW/y/68biOmlJDjDKGG7unkKhK4njB0t2yco8mszYVy06mEkbeIhRLO8bJp+uFtuaDnoteiZTIBkTFRVyABj93yyhE0wK0t2qq0mejdwio+xLSzMwfFqv7m49enbTi8gOom3w18Bh3XucFLY4H+eaGvaJ/+8LtWJ5s+IDTLGSGkxbOjyCtnjvV9PpY2+DeHJ+SAkIWXUeOdx+/xKo2eONmUdhCMpOhq2EEGdzHADZod952kYQekT7wBQmOe9Wg0xXQzWsldH1m7+jgkC5Cwo/OFtekr9QPMZdyYmylEC8Sa4nnHSsnJWoXsor3shjnW14WswsfINDV6arBBuqHpakK5pLGqrlZB1qTzzwDB/aSAuTRyCIIfCbO2zLo0hZZPsUA6GJhUBsoqZ+dMwy2ncnvG4jvsXny9/RYpLbPeE//qeMp2qYUo56t5Rswd1ovx7a45XrIi7HbFOspsZrrRq7fDTjxj38BmYtp5IKpF2UaB16lh3IpVc96u/BKWGeBkAy3p14NLPkKUey/oB9M1JucIcq8bNtRjgAMJjKlR4JtA2Zm/5s115KJDk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
